using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

[Preserve]
public sealed partial class BGExample : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5457119010249193303UL,17645819871656334991UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.Int32 table_id
	{
		get => _table_id[Index];
		set => _table_id.SetValue(this, value);
	}
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_table_id;
	public static BansheeGz.BGDatabase.BGFieldInt _table_id => _ufle12jhs77_table_id ?? (_ufle12jhs77_table_id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5575700446128180883UL, 10554769894094815656UL), () => _ufle12jhs77_table_id = null));
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4894063484788899755UL, 3620164885828834958UL), () => _ufle12jhs77_name = null));
	private BGExample() : base(MetaDefault) {}
	private BGExample(BGId id) : base(MetaDefault, id) {}
	private BGExample(BGMetaEntity meta) : base(meta) {}
	private BGExample(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static BGExample FindEntity(Predicate<BGExample> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<BGExample> FindEntities(Predicate<BGExample> filter, List<BGExample> result=null, Comparison<BGExample> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<BGExample> action, Predicate<BGExample> filter=null, Comparison<BGExample> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static BGExample GetEntity(BGId entityId) => (BGExample) MetaDefault.GetEntity(entityId);
	public static BGExample GetEntity(int index) => (BGExample) MetaDefault[index];
	public static BGExample GetEntity(string entityName) => (BGExample) MetaDefault.GetEntity(entityName);
	public static BGExample NewEntity() => (BGExample) MetaDefault.NewEntity();
	public static BGExample NewEntity(BGId entityId) => (BGExample) MetaDefault.NewEntity(entityId);
	public static BGExample NewEntity(Action<BGExample> callback) => (BGExample) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((BGExample)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5457119010249193303UL,17645819871656334991UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_table_id = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5575700446128180883UL, 10554769894094815656UL));
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4894063484788899755UL, 3620164885828834958UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_table_id = null;
		_ufle12jhs77_name = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BGExample(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BGExample(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "Example";
		public const string table_id = "table_id";
		public const string name = "name";
	}
}

[Preserve]
public static class BGCodeGenRuntimeInitializer
{
	[Preserve]
	public static void InitializeCodeGenRuntime() => BGExample.InitializeCodeGenRuntime();
	[Preserve]
	public static void ReleaseCodeGenRuntime() => BGExample.ReleaseCodeGenRuntime();
}
#pragma warning restore 414
